# Generated by Django 3.2.17 on 2023-06-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.BinaryField()),
                ('lastName', models.BinaryField()),
                ('middleName', models.BinaryField()),
                ('login', models.CharField(max_length=35, unique=True)),
                ('password', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('role', models.CharField(max_length=35)),
                ('date_registration', models.DateTimeField()),
            ],
        ),
    ]
